language: python
python:
  - "3.2"
  - "3.3"

before_install: 
    - sudo apt-get -y update
    - sudo apt-get -y install libigraph0

# command to install dependencies
install: "pip install -r pip_requirements.txt --use-mirrors"

# command to run tests
script: PYTHONPATH='.' ./run_tests.sh
